gha: fix issue when caching virtual environments
Whenever the `setup-python` action would provide a new patch version of the python (as it happened with 3.10.4 -> 3.10.5), it'd break the caching of the virtual environment in the nox and would throw following (cryptic) error:

```
Error: python is not installed into the virtualenv, it is located at /opt/hostedtoolcache/Python/3.10.5/x64/bin/python. Pass external=True into run() to explicitly allow this.
```

It seems it's because the virtualenv has a broken symlink to the old interpreter that does not exist after the update.

https://github.com/actions/setup-python/issues/182 may be related.

With this change, the cache key now depends on the full python version instead of just major.minor. So this issue should hopefully not happen again, and automatically get invalidated.